from typing import Dict
import torch
import torch.nn as nn
from typing import Callable, List

class SCMNode(Callable):
    """
    Base class for a node in a Structural Causal Model (SCM).
    This class is intended to be subclassed for specific types of nodes.
    :param name: Name of the node.
    """

    def __init__(self, name: str):
        """
        Base class for a node in a Structural Causal Model (SCM).

        :param name: Name of the node.
        """
        self.name = name.upper()

    def __call__(self, **kwargs):
        """
        Call method to allow instances of this class to be called like functions.
        This method should be overridden in subclasses to implement specific behavior.
        """
        raise NotImplementedError("Subclasses must implement this method.")

    def do_intervention(self, sample_generator: Callable[..., torch.Tensor]) -> None:
        """
        Perform a do-intervention on this node.
        This method should be overridden in subclasses to implement specific intervention behavior.
        """
        raise NotImplementedError("Subclasses must implement this method.")

class ExogenousNode(SCMNode):
    def __init__(self, name: str, distribution: Callable[..., torch.Tensor]):
        """
        Represents an exogenous node in a Structural Causal Model (SCM).

        :param name: Name of the node.
        :param distribution: Function that generates samples for this node.
        """
        super().__init__(name)
        self.distribution = distribution

    def __call__(self, **distribution_kwargs):
        """
        Generate samples for the exogenous node using the specified distribution.

        :param distribution_kwargs: Keyword arguments to pass to the distribution function.
        :return: Samples generated by the distribution function.
        """
        return self.distribution(**distribution_kwargs)

    def do_intervention(self, distribution: Callable[..., torch.Tensor]):
        """
        Perform a do-intervention on the exogenous node by setting a new distribution.
        :param distribution: New distribution function to use for this node.
        """
        self.distribution = distribution


class EndogenousNode(SCMNode):
    def __init__(self, name: str, scm_eq: Callable[..., torch.Tensor], parents: List[str] = None):
        """
        Represents an endogenous node in a Structural Causal Model (SCM).

        :param name: Name of the node.
        :param scm_eq: Function that defines the structural equation for this node.
        :param parents: List of names of parent nodes for this node.
        """
        super().__init__(name)
        self.scm_eq = scm_eq
        self.parents = [parent.upper() for parent in parents] if parents else []

    def __call__(self, **kwargs: Dict[str, torch.Tensor]) -> torch.Tensor:
        """
        Compute the value of the endogenous node based on its parents.

        :param kwargs: Keyword arguments where each key is a parent name and each value 
                       is a tensor representing the parent's value.
        :return: Value computed by the structural equation for this node.
        """
        parent_values = [kwargs[parent] for parent in self.parents] # list of tensors of shape (batch_size, num_samples)
        parent_tensors = torch.stack(parent_values, dim=-1) # shape (batch_size, num_samples, num_parents)
        return self.scm_eq(parent_tensors)

    def do_intervention(self, scm_eq: Callable[..., torch.Tensor]) -> None:
        """
        Perform a do-intervention on the endogenous node by setting a new structural equation.
        
        :param scm_eq: New structural equation function to use for this node.
        """
        self.scm_eq = scm_eq

    def parent_indices(self, parents: List[str]) -> torch.Tensor:
        """
        Get the indices of this node's parents in the provided list of parent names.

        :param parents: List of parent names to search.
        :return: Tensor of indices corresponding to this node's parents.
        """
        indices = [i for i, parent in enumerate(self.parents) if parent in parents]
        return torch.tensor(indices, dtype=torch.long)

    def set_parent_weight(self, parent: str, weight: float) -> None:
        """
        Set the weight of a specific parent in the structural equation.

        :param parent: Name of the parent whose weight should be set.
        :param weight: New weight value to assign to the parent.
        """
        if not callable(getattr(self.scm_eq, "set_weight", None)):
            raise NotImplementedError("The structural equation does not support setting specific parent weights.")

        index = self.parent_indices([parent])
        self.scm_eq.set_weight(index.item(), weight)

    def remove_parents_causal_influence(self, parents: List[str]) -> None:
        """
        Remove the causal influence of specified parents by zeroing out their weights in the structural equation.

        :param parents: List of parent names whose influence should be removed.
        """
        if not callable(getattr(self.scm_eq, "zero_specific_weights", None)):
            raise NotImplementedError("The structural equation does not support zeroing specific weights.")

        indices = self.parent_indices(parents)
        self.scm_eq.zero_specific_weights(indices)

    def resample_scm_equation(self, *, noise=True, activation=True, layers=True, seed=None):
        """
        Resample components of the structural equation.

        :param noise: Whether to resample the noise component.
        :param activation: Whether to resample the activation function.
        :param layers: Whether to resample the layers of the structural equation.
        :param seed: Random seed for reproducibility.
        """
        se = self.scm_eq
        if noise and hasattr(se, "resample_noise"): se.resample_noise(seed=seed)
        if activation and hasattr(se, "resample_activation"): se.resample_activation(seed=seed)
        if layers and hasattr(se, "reinit_layers"): se.reinit_layers(seed=seed)
